server:
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO

mercadopago:
  access_token: 'YOUR_ACCESS_TOKEN_HERE'
  integrator_id: 'YOUR_INTEGRATOR_ID_HERE'
  notification_url: 'YOUR_NOTIFICATION_URL_HERE'